/*
 * This file is generated by jOOQ.
 */
package models.tables.records


import java.time.LocalDateTime

import models.tables.Request

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record7
import org.jooq.Row7
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RequestRecord() : UpdatableRecordImpl<RequestRecord>(Request.REQUEST), Record7<Int?, Long?, Long?, Long?, Long?, LocalDateTime?, Int?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var guild: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var thread: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var owner: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var headerMessage: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open var createdAt: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var displayId: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row7<Int?, Long?, Long?, Long?, Long?, LocalDateTime?, Int?> = super.fieldsRow() as Row7<Int?, Long?, Long?, Long?, Long?, LocalDateTime?, Int?>
    override fun valuesRow(): Row7<Int?, Long?, Long?, Long?, Long?, LocalDateTime?, Int?> = super.valuesRow() as Row7<Int?, Long?, Long?, Long?, Long?, LocalDateTime?, Int?>
    override fun field1(): Field<Int?> = Request.REQUEST.ID
    override fun field2(): Field<Long?> = Request.REQUEST.GUILD
    override fun field3(): Field<Long?> = Request.REQUEST.THREAD
    override fun field4(): Field<Long?> = Request.REQUEST.OWNER
    override fun field5(): Field<Long?> = Request.REQUEST.HEADER_MESSAGE
    override fun field6(): Field<LocalDateTime?> = Request.REQUEST.CREATED_AT
    override fun field7(): Field<Int?> = Request.REQUEST.DISPLAY_ID
    override fun component1(): Int? = id
    override fun component2(): Long? = guild
    override fun component3(): Long? = thread
    override fun component4(): Long? = owner
    override fun component5(): Long? = headerMessage
    override fun component6(): LocalDateTime? = createdAt
    override fun component7(): Int? = displayId
    override fun value1(): Int? = id
    override fun value2(): Long? = guild
    override fun value3(): Long? = thread
    override fun value4(): Long? = owner
    override fun value5(): Long? = headerMessage
    override fun value6(): LocalDateTime? = createdAt
    override fun value7(): Int? = displayId

    override fun value1(value: Int?): RequestRecord {
        this.id = value
        return this
    }

    override fun value2(value: Long?): RequestRecord {
        this.guild = value
        return this
    }

    override fun value3(value: Long?): RequestRecord {
        this.thread = value
        return this
    }

    override fun value4(value: Long?): RequestRecord {
        this.owner = value
        return this
    }

    override fun value5(value: Long?): RequestRecord {
        this.headerMessage = value
        return this
    }

    override fun value6(value: LocalDateTime?): RequestRecord {
        this.createdAt = value
        return this
    }

    override fun value7(value: Int?): RequestRecord {
        this.displayId = value
        return this
    }

    override fun values(value1: Int?, value2: Long?, value3: Long?, value4: Long?, value5: Long?, value6: LocalDateTime?, value7: Int?): RequestRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        return this
    }

    /**
     * Create a detached, initialised RequestRecord
     */
    constructor(id: Int? = null, guild: Long? = null, thread: Long? = null, owner: Long? = null, headerMessage: Long? = null, createdAt: LocalDateTime? = null, displayId: Int? = null): this() {
        this.id = id
        this.guild = guild
        this.thread = thread
        this.owner = owner
        this.headerMessage = headerMessage
        this.createdAt = createdAt
        this.displayId = displayId
    }
}
