/*
 * This file is generated by jOOQ.
 */
package models.tables.records


import models.enums.State
import models.tables.RequestInfo

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RequestInfoRecord() : UpdatableRecordImpl<RequestInfoRecord>(RequestInfo.REQUEST_INFO), Record5<Int?, String?, String?, State?, Array<String?>?> {

    open var request: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var title: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var detail: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var state: State?
        set(value): Unit = set(3, value)
        get(): State? = get(3) as State?

    open var tags: Array<String?>?
        set(value): Unit = set(4, value)
        get(): Array<String?>? = get(4) as Array<String?>?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Int?, String?, String?, State?, Array<String?>?> = super.fieldsRow() as Row5<Int?, String?, String?, State?, Array<String?>?>
    override fun valuesRow(): Row5<Int?, String?, String?, State?, Array<String?>?> = super.valuesRow() as Row5<Int?, String?, String?, State?, Array<String?>?>
    override fun field1(): Field<Int?> = RequestInfo.REQUEST_INFO.REQUEST
    override fun field2(): Field<String?> = RequestInfo.REQUEST_INFO.TITLE
    override fun field3(): Field<String?> = RequestInfo.REQUEST_INFO.DETAIL
    override fun field4(): Field<State?> = RequestInfo.REQUEST_INFO.STATE
    override fun field5(): Field<Array<String?>?> = RequestInfo.REQUEST_INFO.TAGS
    override fun component1(): Int? = request
    override fun component2(): String? = title
    override fun component3(): String? = detail
    override fun component4(): State? = state
    override fun component5(): Array<String?>? = tags
    override fun value1(): Int? = request
    override fun value2(): String? = title
    override fun value3(): String? = detail
    override fun value4(): State? = state
    override fun value5(): Array<String?>? = tags

    override fun value1(value: Int?): RequestInfoRecord {
        this.request = value
        return this
    }

    override fun value2(value: String?): RequestInfoRecord {
        this.title = value
        return this
    }

    override fun value3(value: String?): RequestInfoRecord {
        this.detail = value
        return this
    }

    override fun value4(value: State?): RequestInfoRecord {
        this.state = value
        return this
    }

    override fun value5(value: Array<String?>?): RequestInfoRecord {
        this.tags = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: State?, value5: Array<String?>?): RequestInfoRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised RequestInfoRecord
     */
    constructor(request: Int? = null, title: String? = null, detail: String? = null, state: State? = null, tags: Array<String?>? = null): this() {
        this.request = request
        this.title = title
        this.detail = detail
        this.state = state
        this.tags = tags
    }
}
