/*
 * This file is generated by jOOQ.
 */
package models.tables.records


import models.tables.Subscription

import org.jooq.Field
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SubscriptionRecord() : UpdatableRecordImpl<SubscriptionRecord>(Subscription.SUBSCRIPTION), Record3<Long?, Long?, Int?> {

    open var user: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var guild: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var request: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record3<Long?, Long?, Int?> = super.key() as Record3<Long?, Long?, Int?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Long?, Long?, Int?> = super.fieldsRow() as Row3<Long?, Long?, Int?>
    override fun valuesRow(): Row3<Long?, Long?, Int?> = super.valuesRow() as Row3<Long?, Long?, Int?>
    override fun field1(): Field<Long?> = Subscription.SUBSCRIPTION.USER
    override fun field2(): Field<Long?> = Subscription.SUBSCRIPTION.GUILD
    override fun field3(): Field<Int?> = Subscription.SUBSCRIPTION.REQUEST
    override fun component1(): Long? = user
    override fun component2(): Long? = guild
    override fun component3(): Int? = request
    override fun value1(): Long? = user
    override fun value2(): Long? = guild
    override fun value3(): Int? = request

    override fun value1(value: Long?): SubscriptionRecord {
        this.user = value
        return this
    }

    override fun value2(value: Long?): SubscriptionRecord {
        this.guild = value
        return this
    }

    override fun value3(value: Int?): SubscriptionRecord {
        this.request = value
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: Int?): SubscriptionRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised SubscriptionRecord
     */
    constructor(user: Long? = null, guild: Long? = null, request: Int? = null): this() {
        this.user = user
        this.guild = guild
        this.request = request
    }
}
