/*
 * This file is generated by jOOQ.
 */
package models.tables


import java.util.function.Function

import models.Public
import models.keys.KEY
import models.tables.records.GuildRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Guild(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, GuildRecord>?,
    aliased: Table<GuildRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<GuildRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.guild</code>
         */
        val GUILD: Guild = Guild()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GuildRecord> = GuildRecord::class.java

    /**
     * The column <code>public.guild.id</code>.
     */
    val ID: TableField<GuildRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.guild.container</code>.
     */
    val CONTAINER: TableField<GuildRecord, Long?> = createField(DSL.name("container"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.guild.user_role</code>.
     */
    val USER_ROLE: TableField<GuildRecord, Long?> = createField(DSL.name("user_role"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.guild.admin_role</code>.
     */
    val ADMIN_ROLE: TableField<GuildRecord, Long?> = createField(DSL.name("admin_role"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.guild.manager_role</code>.
     */
    val MANAGER_ROLE: TableField<GuildRecord, Long?> = createField(DSL.name("manager_role"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<GuildRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<GuildRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.guild</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.guild</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.guild</code> table reference
     */
    constructor(): this(DSL.name("guild"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, GuildRecord>): this(Internal.createPathAlias(child, key), child, key, GUILD, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<GuildRecord> = KEY
    override fun `as`(alias: String): Guild = Guild(DSL.name(alias), this)
    override fun `as`(alias: Name): Guild = Guild(alias, this)
    override fun `as`(alias: Table<*>): Guild = Guild(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Guild = Guild(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Guild = Guild(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Guild = Guild(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Long?, Long?, Long?, Long?, Long?> = super.fieldsRow() as Row5<Long?, Long?, Long?, Long?, Long?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Long?, Long?, Long?, Long?, Long?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Long?, Long?, Long?, Long?, Long?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
