/*
 * This file is generated by jOOQ.
 */
package models.tables


import java.util.function.Function

import models.Public
import models.enums.State
import models.keys.TABLE_NAME_PKEY
import models.tables.records.RequestInfoRecord

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row5
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RequestInfo(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, RequestInfoRecord>?,
    aliased: Table<RequestInfoRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<RequestInfoRecord>(
    alias,
    Public.PUBLIC,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>public.request_info</code>
         */
        val REQUEST_INFO: RequestInfo = RequestInfo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RequestInfoRecord> = RequestInfoRecord::class.java

    /**
     * The column <code>public.request_info.request</code>.
     */
    val REQUEST: TableField<RequestInfoRecord, Int?> = createField(DSL.name("request"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.request_info.title</code>.
     */
    val TITLE: TableField<RequestInfoRecord, String?> = createField(DSL.name("title"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.request_info.detail</code>.
     */
    val DETAIL: TableField<RequestInfoRecord, String?> = createField(DSL.name("detail"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.request_info.state</code>.
     */
    val STATE: TableField<RequestInfoRecord, State?> = createField(DSL.name("state"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field("'opening'::state", SQLDataType.VARCHAR)).asEnumDataType(models.enums.State::class.java), this, "")

    /**
     * The column <code>public.request_info.tags</code>.
     */
    val TAGS: TableField<RequestInfoRecord, Array<String?>?> = createField(DSL.name("tags"), SQLDataType.VARCHAR(20).getArrayDataType(), this, "")

    private constructor(alias: Name, aliased: Table<RequestInfoRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<RequestInfoRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>public.request_info</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.request_info</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.request_info</code> table reference
     */
    constructor(): this(DSL.name("request_info"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, RequestInfoRecord>): this(Internal.createPathAlias(child, key), child, key, REQUEST_INFO, null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<RequestInfoRecord> = TABLE_NAME_PKEY
    override fun `as`(alias: String): RequestInfo = RequestInfo(DSL.name(alias), this)
    override fun `as`(alias: Name): RequestInfo = RequestInfo(alias, this)
    override fun `as`(alias: Table<*>): RequestInfo = RequestInfo(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RequestInfo = RequestInfo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RequestInfo = RequestInfo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RequestInfo = RequestInfo(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row5<Int?, String?, String?, State?, Array<String?>?> = super.fieldsRow() as Row5<Int?, String?, String?, State?, Array<String?>?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, String?, State?, Array<String?>?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, String?, State?, Array<String?>?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
