/*
 * This file is generated by jOOQ.
 */
package models


import kotlin.collections.List

import models.tables.Guild
import models.tables.Request
import models.tables.RequestInfo
import models.tables.Subscription
import models.tables.Todo

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.guild</code>.
     */
    val GUILD: Guild get() = Guild.GUILD

    /**
     * The table <code>public.request</code>.
     */
    val REQUEST: Request get() = Request.REQUEST

    /**
     * The table <code>public.request_info</code>.
     */
    val REQUEST_INFO: RequestInfo get() = RequestInfo.REQUEST_INFO

    /**
     * The table <code>public.subscription</code>.
     */
    val SUBSCRIPTION: Subscription get() = Subscription.SUBSCRIPTION

    /**
     * The table <code>public.todo</code>.
     */
    val TODO: Todo get() = Todo.TODO

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Guild.GUILD,
        Request.REQUEST,
        RequestInfo.REQUEST_INFO,
        Subscription.SUBSCRIPTION,
        Todo.TODO
    )
}
