/*
 * This file is generated by jOOQ.
 */
package models.keys


import models.tables.Guild
import models.tables.Request
import models.tables.RequestInfo
import models.tables.Subscription
import models.tables.Todo
import models.tables.records.GuildRecord
import models.tables.records.RequestInfoRecord
import models.tables.records.RequestRecord
import models.tables.records.SubscriptionRecord
import models.tables.records.TodoRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val KEY: UniqueKey<GuildRecord> = Internal.createUniqueKey(Guild.GUILD, DSL.name("key"), arrayOf(Guild.GUILD.ID), true)
val REQUEST_PK: UniqueKey<RequestRecord> = Internal.createUniqueKey(Request.REQUEST, DSL.name("request_pk"), arrayOf(Request.REQUEST.ID), true)
val TABLE_NAME_PKEY: UniqueKey<RequestInfoRecord> = Internal.createUniqueKey(RequestInfo.REQUEST_INFO, DSL.name("table_name_pkey"), arrayOf(RequestInfo.REQUEST_INFO.REQUEST), true)
val SUBSCRIPTION_PK: UniqueKey<SubscriptionRecord> = Internal.createUniqueKey(Subscription.SUBSCRIPTION, DSL.name("subscription_pk"), arrayOf(Subscription.SUBSCRIPTION.USER, Subscription.SUBSCRIPTION.REQUEST), true)
val TODO_PKEY: UniqueKey<TodoRecord> = Internal.createUniqueKey(Todo.TODO, DSL.name("todo_pkey"), arrayOf(Todo.TODO.USER), true)
